### ISSUE TITLE
Algorithm improvements

### ISSUE THREAD

**Issue by TerrorBite** [QL0R/Traffic-Confuser#11]
It looks like this project currently only sends single requests fairly constantly to random sites. Data analysis would easily be able to filter this out from normal user browsing behaviour.

A better way to achieve the goals of this project would be:

* Pick a random URL. There's a few ways to do this:
    * Pick a domain name from a static list like the [Alexa Top Million](http://s3.amazonaws.com/alexa-static/top-1m.csv.zip) (outdated, anyone remember Alexa rankings?) or similar dataset, and visit the root page of that domain.
    * Make an API call to a link aggregation site, such as Reddit /r/all or /r/random, and look for links to follow.
    * Grab Twitter trending and look for links.
    * URL shorteners tend to use sequential IDs. Pick a URL shortener, generate a random ID, and see where it takes you.
* Issue a request to your randomly selected URL. When the response arrives, look for SRC links to images, CSS and JavaScript and grab all those too, to simulate a web browser loading page resources. Don't actually do anything with the files, just throw out the data.
* Wait for some period of time between 5-60 seconds to simulate user interaction.
* Look for hyperlink tags in the HTML to other pages. Follow one at random. Repeat the process.
* After some period of time following links from page to page, pick a completely new link. Before browsing the new link, delay for a random number of minutes.
* Optionally cease activity during certain time periods, such as overnight, when a human would be asleep.

The only data that an ISP can see within each HTTPS request is the SNI (server name indication) header that is sent to the server to say what domain name you're trying to connect to, and the SSL certificate that the server sends back (which will also contain the domain name). After this, the connection is encrypted, and the ISP cannot see the full URL being requested, nor the content that is being sent back, as this is all encrypted.

However, the ISP will observe metadata about the connection, such as the IP address being connected to, the time and duration of the connection, and the amount of data transferred, and they can infer information from this metadata. The reason for the complexity of simulating real browsing behaviour despite the ISP being unable to see the content, is to generate realistic metadata.

Keep in mind that real browsers will open several connections to the same host and then reuse each connection for multiple requests, sending requests in parallel to speed up loading page resources. A good HTTP library like Requests for Python will automatically do the same thing if you use its features correctly.

----

**Edited to add:** This issue is a copy of [a comment I left on a post on Reddit /r/masterhacker](https://www.reddit.com/r/masterhacker/comments/xxdwbt/_/ircqab4) which featured this tool.

**Comment by 0xDarkSky** [comment]
"_Pick a random URL. There's a few ways to do this:_ "

It's already doing that. I am not sure if you have looked into the code. But the code is literally picking up a random site from the website list in the .txt file and then sending an HTTP request to one of them.

The project is no longer maintained so I'm not sure if I'm going to be updating anything.

I assume you haven't looked into my other repos? A remastered version of this current project exists.
https://github.com/0xDarkSky/Vexatious
It opens up websites with chrome. You can choose to use chrome headless. It's by far the most realistic way to send requests if you ask me.

I have checked the post on Reddit. 

The guy who posted it is creating an actual Twitter "bruteforce tool" for a few weeks now (which is obviously not working), so I don't think I have to state the obvious about the guy who made the post.

**"Hiding his traffic with 1 request at a time"** if I was to implement threading and send hundreds of requests at a time, that would break the whole point of this project lol. The point was to imitate traffic that looks like it's normal traffic. 
Would a hundred requests a second look like legit web traffic tho? I don't think so.
